package ae

import "github.com/godicom-dev/godicom/uid"

// AllStorageSOPClasses lists Storage Service Class SOP Class UIDs
// (pynetdicom `_STORAGE_CLASSES` / AllStoragePresentationContexts).
// Prefer this for a generic Storage SCP:
//
//	AcceptedAbstractSyntaxes: ae.AllStorageSOPClasses,
//
// The entries name godicom/uid constants instead of repeating UID strings, so a
// SOP class is spelled out once — in godicom's dictionary — and a name that does
// not match its UID is a compile error rather than a misleading comment. For one
// SOP class, or a few, take them from the same place:
//
//	AcceptedAbstractSyntaxes: ae.UIDStrings(uid.CTImageStorage, uid.MRImageStorage),
//
// The set follows pynetdicom/pynetdicom/sop_class.py; keep it in sync when
// upgrading the submodule (TestAllStorageSOPClassesMatchPynetdicom checks this
// where the submodule is checked out).
var AllStorageSOPClasses = UIDStrings(
	uid.ComputedRadiographyImageStorage,
	uid.DigitalXRayImageStorageForPresentation,
	uid.DigitalXRayImageStorageForProcessing,
	uid.DigitalMammographyXRayImageStorageForPresentation,
	uid.DigitalMammographyXRayImageStorageForProcessing,
	uid.DigitalIntraOralXRayImageStorageForPresentation,
	uid.DigitalIntraOralXRayImageStorageForProcessing,
	uid.EncapsulatedPDFStorage,
	uid.EncapsulatedCDAStorage,
	uid.EncapsulatedSTLStorage,
	uid.EncapsulatedOBJStorage,
	uid.EncapsulatedMTLStorage,
	uid.GrayscaleSoftcopyPresentationStateStorage,
	uid.SegmentedVolumeRenderingVolumetricPresentationStateStorage,
	uid.MultipleVolumeRenderingVolumetricPresentationStateStorage,
	uid.VariableModalityLUTSoftcopyPresentationStateStorage,
	uid.ColorSoftcopyPresentationStateStorage,
	uid.PseudoColorSoftcopyPresentationStateStorage,
	uid.BlendingSoftcopyPresentationStateStorage,
	uid.XAXRFGrayscaleSoftcopyPresentationStateStorage,
	uid.GrayscalePlanarMPRVolumetricPresentationStateStorage,
	uid.CompositingPlanarMPRVolumetricPresentationStateStorage,
	uid.AdvancedBlendingPresentationStateStorage,
	uid.VolumeRenderingVolumetricPresentationStateStorage,
	uid.XRayAngiographicImageStorage,
	uid.EnhancedXAImageStorage,
	uid.XRayRadiofluoroscopicImageStorage,
	uid.EnhancedXRFImageStorage,
	uid.PositronEmissionTomographyImageStorage,
	uid.LegacyConvertedEnhancedPETImageStorage,
	uid.XRay3DAngiographicImageStorage,
	uid.XRay3DCraniofacialImageStorage,
	uid.BreastTomosynthesisImageStorage,
	uid.BreastProjectionXRayImageStorageForPresentation,
	uid.BreastProjectionXRayImageStorageForProcessing,
	uid.EnhancedPETImageStorage,
	uid.BasicStructuredDisplayStorage,
	uid.IntravascularOpticalCoherenceTomographyImageStorageForPresentation,
	uid.IntravascularOpticalCoherenceTomographyImageStorageForProcessing,
	uid.CTImageStorage,
	uid.EnhancedCTImageStorage,
	uid.LegacyConvertedEnhancedCTImageStorage,
	uid.NuclearMedicineImageStorage,
	uid.CTPerformedProcedureProtocolStorage,
	uid.XAPerformedProcedureProtocolStorage,
	uid.UltrasoundMultiFrameImageStorage,
	uid.ParametricMapStorage,
	uid.MRImageStorage,
	uid.EnhancedMRImageStorage,
	uid.MRSpectroscopyStorage,
	uid.EnhancedMRColorImageStorage,
	uid.LegacyConvertedEnhancedMRImageStorage,
	uid.RTImageStorage,
	uid.RTPhysicianIntentStorage,
	uid.RTSegmentAnnotationStorage,
	uid.RTRadiationSetStorage,
	uid.CArmPhotonElectronRadiationStorage,
	uid.TomotherapeuticRadiationStorage,
	uid.RoboticArmRadiationStorage,
	uid.RTRadiationRecordSetStorage,
	uid.RTRadiationSalvageRecordStorage,
	uid.TomotherapeuticRadiationRecordStorage,
	uid.CArmPhotonElectronRadiationRecordStorage,
	uid.RTDoseStorage,
	uid.RoboticRadiationRecordStorage,
	uid.RTRadiationSetDeliveryInstructionStorage,
	uid.RTTreatmentPreparationStorage,
	uid.EnhancedRTImageStorage,
	uid.EnhancedContinuousRTImageStorage,
	uid.RTPatientPositionAcquisitionInstructionStorage,
	uid.RTStructureSetStorage,
	uid.RTBeamsTreatmentRecordStorage,
	uid.RTPlanStorage,
	uid.RTBrachyTreatmentRecordStorage,
	uid.RTTreatmentSummaryRecordStorage,
	uid.RTIonPlanStorage,
	uid.RTIonBeamsTreatmentRecordStorage,
	uid.UltrasoundImageStorage,
	uid.EnhancedUSVolumeStorage,
	uid.PhotoacousticImageStorage,
	uid.RawDataStorage,
	uid.SpatialRegistrationStorage,
	uid.SpatialFiducialsStorage,
	uid.DeformableSpatialRegistrationStorage,
	uid.SegmentationStorage,
	uid.SurfaceSegmentationStorage,
	uid.TractographyResultsStorage,
	uid.LabelMapSegmentationStorage,
	uid.HeightMapSegmentationStorage,
	uid.RealWorldValueMappingStorage,
	uid.SurfaceScanMeshStorage,
	uid.SurfaceScanPointCloudStorage,
	uid.SecondaryCaptureImageStorage,
	uid.MultiFrameSingleBitSecondaryCaptureImageStorage,
	uid.MultiFrameGrayscaleByteSecondaryCaptureImageStorage,
	uid.MultiFrameGrayscaleWordSecondaryCaptureImageStorage,
	uid.MultiFrameTrueColorSecondaryCaptureImageStorage,
	uid.VLEndoscopicImageStorage,
	uid.VideoEndoscopicImageStorage,
	uid.VLMicroscopicImageStorage,
	uid.VideoMicroscopicImageStorage,
	uid.VLSlideCoordinatesMicroscopicImageStorage,
	uid.VLPhotographicImageStorage,
	uid.VideoPhotographicImageStorage,
	uid.OphthalmicPhotography8BitImageStorage,
	uid.OphthalmicPhotography16BitImageStorage,
	uid.StereometricRelationshipStorage,
	uid.OphthalmicTomographyImageStorage,
	uid.WideFieldOphthalmicPhotographyStereographicProjectionImageStorage,
	uid.WideFieldOphthalmicPhotography3DCoordinatesImageStorage,
	uid.OphthalmicOpticalCoherenceTomographyEnFaceImageStorage,
	uid.OphthalmicOpticalCoherenceTomographyBscanVolumeAnalysisStorage,
	uid.VLWholeSlideMicroscopyImageStorage,
	uid.DermoscopicPhotographyImageStorage,
	uid.ConfocalMicroscopyImageStorage,
	uid.ConfocalMicroscopyTiledPyramidalImageStorage,
	uid.LensometryMeasurementsStorage,
	uid.AutorefractionMeasurementsStorage,
	uid.KeratometryMeasurementsStorage,
	uid.SubjectiveRefractionMeasurementsStorage,
	uid.VisualAcuityMeasurementsStorage,
	uid.SpectaclePrescriptionReportStorage,
	uid.OphthalmicAxialMeasurementsStorage,
	uid.IntraocularLensCalculationsStorage,
	uid.MacularGridThicknessAndVolumeReportStorage,
	uid.OphthalmicVisualFieldStaticPerimetryMeasurementsStorage,
	uid.OphthalmicThicknessMapStorage,
	uid.CornealTopographyMapStorage,
	uid.BasicTextSRStorage,
	uid.EnhancedSRStorage,
	uid.ComprehensiveSRStorage,
	uid.Comprehensive3DSRStorage,
	uid.ExtensibleSRStorage,
	uid.ProcedureLogStorage,
	uid.MammographyCADSRStorage,
	uid.KeyObjectSelectionDocumentStorage,
	uid.ChestCADSRStorage,
	uid.XRayRadiationDoseSRStorage,
	uid.RadiopharmaceuticalRadiationDoseSRStorage,
	uid.ColonCADSRStorage,
	uid.ImplantationPlanSRStorage,
	uid.AcquisitionContextSRStorage,
	uid.SimplifiedAdultEchoSRStorage,
	uid.PatientRadiationDoseSRStorage,
	uid.PlannedImagingAgentAdministrationSRStorage,
	uid.PerformedImagingAgentAdministrationSRStorage,
	uid.EnhancedXRayRadiationDoseSRStorage,
	uid.WaveformAnnotationSRStorage,
	uid.TwelveLeadECGWaveformStorage,
	uid.GeneralECGWaveformStorage,
	uid.AmbulatoryECGWaveformStorage,
	uid.General32bitECGWaveformStorage,
	WaveformPresentationStateStorage,
	WaveformAcquisitionPresentationStateStorage,
	uid.HemodynamicWaveformStorage,
	uid.CardiacElectrophysiologyWaveformStorage,
	uid.BasicVoiceAudioWaveformStorage,
	uid.GeneralAudioWaveformStorage,
	uid.ArterialPulseWaveformStorage,
	uid.RespiratoryWaveformStorage,
	uid.MultichannelRespiratoryWaveformStorage,
	uid.RoutineScalpElectroencephalogramWaveformStorage,
	uid.ElectromyogramWaveformStorage,
	uid.ElectrooculogramWaveformStorage,
	uid.SleepElectroencephalogramWaveformStorage,
	uid.BodyPositionWaveformStorage,
	uid.ContentAssessmentResultsStorage,
	uid.MicroscopyBulkSimpleAnnotationsStorage,
	uid.RTBrachyApplicationSetupDeliveryInstructionStorage,
	uid.RTBeamsDeliveryInstructionStorage,
)

// Storage SOP Classes godicom's UID dictionary does not name yet (godicom
// v0.26.0), spelled out so the list above stays complete. Untyped so they pass
// anywhere a UID string or a uid.UID is wanted; drop them once the dictionary
// catches up (TestStorageSOPClassesGodicomDoesNotName watches for that).
const (
	WaveformPresentationStateStorage            = "1.2.840.10008.5.1.4.1.1.9.100.1"
	WaveformAcquisitionPresentationStateStorage = "1.2.840.10008.5.1.4.1.1.9.100.2"
)
